#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 30, 2019 12:00:23 PM PKT  platform: Linux

import sys

import tkinter.ttk as ttk
#     py3 = True
from tkinter import *
from tkinter import ttk
# import filethread
import time
import tkinter as tk
from PIL import ImageTk, Image
from tkinter.font import Font
import tkinter

w = 0
top_level = 0
root = 0


def init(top, gui, *args, **kwargs):

    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import page
    page.vp_start_gui()
